# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# ActualizarHora = ->
#   fecha = new Date
#   segundos = fecha.getSeconds()
#   minutos = fecha.getMinutes()
#   horas = fecha.getHours()
#   elementoHoras = document.getElementById('pHoras')
#   elementoMinutos = document.getElementById('pMinutos')
#   elementoSegundos = document.getElementById('pSegundos')
#   pSaludo = document.getElementById('contSaludo')
#   elementoHoras.textContent = horas
#   elementoMinutos.textContent = minutos
#   elementoSegundos.textContent = segundos
#   if horas >= 8 and minutos >= 1 and horas < 12
#     pSaludo.textContent = 'buenos días'
 #  if horas >= 12 and minutos >= 1 and horas < 19
#     pSaludo.textContent = 'buenas tardes'
#   if horas >= 19 and minutos >= 1
#     pSaludo.textContent = 'buenas noches'
#   return

#setInterval ActualizarHora, 1000

# ---
# generated by js2coffee 2.2.0